name: Container

on: push

jobs:
  docker-container:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Check Node Version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run Entrypoint
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./entrypoint.sh

  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - "3001:3000"
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user
        -H 'Content-Type: application/json' -d 
        '{\"username\": \"Hello\", \"address\": \"dwded\"}'"
      - name: Get users
        run: curl http://localhost:3001/api/users